[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@superfluid-finance/ethereum-contracts/contracts/=lib/protocol-monorepo/packages/ethereum-contracts/contracts/"
]
gas_reports = ['*']

[fmt]
line_length = 79
tab_width = 4
bracket_spacing = true

# Configs Doc: https://github.com/foundry-rs/foundry/blob/master/config/README.md
